### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by SimonWaldherr** [SimonWaldherr/TextLint#1]
- [ ] check quotation marks
- [ ] check whitespace (especially near punctuation)
- [ ] check word frequency
- [ ] check for common mistakes (eg. dass/das, denn/den, ...)
- [ ] check sentence length
- [ ] check punctuation marks (auto-detect if used as enumeration signs)
- [ ] add more entries to this list
